import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { Toaster } from "sonner";
import { CustomerAuthGate } from "@/components/auth/customer-auth-gate";
import { ReduxProvider } from "@/components/providers/redux-provider";
import "./globals.css";
import { ThemeProvider } from "./theme-provider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ReduxProvider>
          <ThemeProvider>
            <CustomerAuthGate>
              {children}
              <Toaster richColors duration={3000} position="bottom-right" closeButton />
            </CustomerAuthGate>
          </ThemeProvider>
        </ReduxProvider>
      </body>
    </html>
  );
}
